### ISSUE TITLE
Bluetooth not really working after initial install

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#12]
I have been testing current dev branch with a private `inventory` file:
```
[bluetooth_sinks]
172.24.1.196
```
I just added some small fixes to make it work on my bullseye test raspi and the current state is: Immediately after first install, the connection from a mobile seemed to work, but after first connect
* somehow the bluetooth server on the raspi changes its ID to aa:aa:aa:aa:aa:aa (is this bluealsa_aplay?) 
* somehow there is no sound --> missing config in `/etc/acable.conf.d/`**TODO**
* even deleting the devices does not work.

Need more time to debug.

**Comment by Daenou** [comment]
If I understand you correctly, this has somehow been fixed but you now run into an issue with bluealsa-aplay because it can't open the PCM device, right?

**Comment by nis65** [comment]
Did some debugging today:
* upgraded my ansible as I could not implement all with `ansible.builtin.command` and `.shell` stuff to work with 2.9.
* The `bluealsa` acable works out of the box for an ubuntu 2004 client
* reconnect without removing the device with `bluetoothctl`works for both my Nokia and my ubuntu 2004 as clients.
* when connected with my Nokia, I cannot play audio with the `bluealsa` acable. I keep receiving errors about 48k bit rate and hear no sound. This is not an issue with the ubuntu 2004 client
* I [implemented](https://github.com/Daenou/ansible-multiroom-audio/commit/2e26e3927e1398adcecca6f14a9d5acba94eb4a9) an additional acable config `bluediscover` that works similar to `bluealsa`, but uses `arec` to read the sound from bluealsa. This makes my Nokia work fully.

Maybe  `bluealsa` and `bluediscover` should be named differently, as `bluealsa` has another meaning already (the daemon).

I used the following host_vars:
~~~
---

acable_connections:
  - bluediscover

acable_config:
  bluediscover:
    sink: dmix:CARD=sndrpihifiberry,DEV=0

~~~

**Comment by nis65** [comment]
The technical part is now solved, i.e.
* reconnect issue seems to be gone (probably due to buster, due to ....)
* bluediscover is [now implemented "nice enough"](https://github.com/Daenou/ansible-multiroom-audio/commit/b1eaf3e9d9f4221b1ddaa945b4e98303d13a70a4), althouth a solution without polling every second for a connected device would be much nicer.

The naming issue is to be discussed/decided.

**Comment by Daenou** [comment]
@nis65 Please review my current solution

**Comment by nis65** [comment]
Happy with the renaming :-)

I made a small improvement (removed the unneded MAC temp var) to the `bluealsa-workaround-cable` implementation
https://github.com/Daenou/ansible-multiroom-audio/commit/155f47cb6244d565b5a039e55c471fe110eb310c

I hoped to reduce the difference to standard arec/aplay case to one single line within the case statement, but
am not there (yet).

I really don't like your current implementation because it relies on the GLOBAL var feature of a shell script:
In the workaround case, SOURCE is set on line 47, but its value is used on line 37 without any parameter
passing. I do hate global variables, but I can get along when they are more or less constants, i.e. their value
is only set at the very beginning and then left constant before being used in any scope level. But this is not
the case here.

So EITHER 
* we pass SOURCE as explicit argument to arecplaypipe
* OR we return to my [previous implementation](https://github.com/Daenou/ansible-multiroom-audio/commit/b1eaf3e9d9f4221b1ddaa945b4e98303d13a70a4#diff-22e9a4a12b620e958425cdfff3595bb8296b62e74206e72eb35a4dabb57066c9) in the case statement. Maybe the special handling for the workaround could be reduced to one line within the case statement, so it looks nicer. Another idea is to use the ` case`  of alternative matches to make the `case`  clearer:
```
case "$1" in
  bluealsa-cable ) ... ;;
  bluealsa-cable-workaround | * ) ... ;;
esac
```

**Comment by nis65** [comment]
As briefly discussed today: I'll implement the parameter passing option.

**Comment by nis65** [comment]
All issues fixed by https://github.com/Daenou/ansible-multiroom-audio/commit/a00d5cea
