### ISSUE TITLE
Changing host vars can leave stale configs/services

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#15]
During development today, I removed in my host vars an `acable` `bluealsa`. During development, i discovered that I needed a new `acable` type, implemented this and then ran the playbook again. I had to manually 
* stop and remove the systemd unit for `bluealsa`
* remove the `/etc/acable.conf.d/bluealsa.conf` file

I don't know if unneed systemd units / config files could be automatically cleaned up by the playbook...

**Comment by Daenou** [comment]
@nis65 Yes I've already ran into this. Not sure what the general consensus on this is, is the ansible playbook also supposed to be able to "remove" configurations and packages?

For the acable role it would be easy to automatically remove all not specified acable@* systemd units and all acable config files in `/etc/acable.conf,d/`.

My question moreso extends to all the other hosts, should the playbook also be able to remove for example snapclient and snapserver (packages and config)? It wouldn't all be possible of course but I'm not sure if this is the idea of configuring hosts with ansible.

**Comment by nis65** [comment]
@Daenou: I think we can limit ourselves to clean up things that might break something. As long as we all dnsnoop/dmix, "loose" cables do not break really something, but if I e.g. decide to remove the cable from bluealsa to the hifiberry because I want bluealsa to go to an aloop device or simply not connect (and e.g. connect manually using mpd), I don't want to hear bluetooth sound any more directly. So for acables, I am clearly pro cleanup (i.e. all cables are defined by ansible config only, no support for manual cabling without ansible).

For the other roles, I can't comment yet, I need to use them first... :smile:

**Comment by Daenou** [comment]
Hint Robert De Bock: use ansible service_facts

**Comment by nis65** [comment]
As I have changed the needed ansible data structure for `acable` and added the same to `snapclient` any implementation of that functionality should be done using that structure (see #16/#26).
And yes, I think that "cleanup" should be done for both acable and snapclient (i.e. when I deconfigure a certain snapclient, I want to have it removed by ansible).

**Comment by nis65** [comment]
This is still a goal, but now we have two targets: acable and snapclient. :-)

**Comment by nis65** [comment]
Well. Not a top prio. But i already branched off `dev`: `reset-snapclients`. Will give it a try...

**Comment by nis65** [comment]
Implemented for snapclients in 038f76b, to be ported to acables after merge.

**Comment by nis65** [comment]
Issue is solved in `dev` by #29, to be implemented for acables.

**Comment by nis65** [comment]
fixed in #47
