### ISSUE TITLE
bluealsa only in buster, not in bullseye :frowning_face: 

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#18]
When starting with a plain bullseye image (e.g. https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/2021-10-30-raspios-bullseye-armhf-lite.zip), the `bluealsa` package cannot be installed. 

Workaround: Manually configure the old buster repo as apt source:
~~~
deb http://archive.raspberrypi.org/debian/ buster main
~~~
Until now, I did not see any drawbacks (like other unwanted packages from buster being installed).

**Comment by nis65** [comment]
Do this as root on your pi:
~~~
cat << EOF > /etc/apt/sources.list.d/busterforbluealsa.list
deb http://archive.raspberrypi.org/debian/ buster main 
EOF
~~~

**Comment by JJ-Author** [comment]
I used the [raspbian testing repository](https://tech.borpin.co.uk/2019/12/17/install-a-package-from-the-testing-repository/) and installed the newer `bluez-alsa-utils` package containing bluealsa 3.0.0 which is newer than the one from buster and solved e.g. volume control issues via Bluetooth from my Android device
