### ISSUE TITLE
Rename "snapserver_alsadevice" to "snapserver_alsasource" in snapserver.conf.j2

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#19]
I think we should try to name all devices by their kind (*source* vs *sink*) to be consistent.

If you agree, I'll do it :smile:

**Comment by nis65** [comment]
Signal from @Daenou : yes do it :-)

**Comment by Daenou** [comment]
Yes do it!

**Comment by Daenou** [comment]
Functionality is in dev branch
