### ISSUE TITLE
Restructure bluetooth role

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#23]
In order to create a Bluetooth A2DP audio input, three roles have to be called: `bluetoothd`, `a2dp_agent` and `bluealsa`.

In addition, you need `acables` and configure a cable with one of the two special bluetooth names.

On the other hand, as long as you don't use one of those special names, you can make use of `acables` alone.

So the three Bluetooth roles are actually an 'enabler' for the special bluetooth acable names.

I propose to merge the three roles into a single new one called `acables_bluetooth` and its `main.yml` would basically include the current three tasks. I can't see a use case for an independent use of one of the three current Bluetooth roles.

**Comment by Daenou** [comment]
I like this, but the naming `acables_bluetooth` is confusing to me

**Comment by nis65** [comment]
Will implement this sometime. I agree that naming is to be discussed. Will try to make up sth better.

**Comment by nis65** [comment]
Almost done in #30 .
