### ISSUE TITLE
acable not stable

### ISSUE THREAD

**Issue by nis65** [Daenou/ansible-multiroom-audio#40]
I have a running acable copying the hardware input `dsnoop` audio to the loopback `dmix` device in order to be consumed by the local snapserver.

I usually leave my raspi running over night. Since I switched from my manual configuration to these roles, I usually had the following issue:
* Listening to an analog source for the whole evening without issues
* Go to sleep (let the raspi run)
* In the morning, start to play another analog source
* Result: The sound was "chopped" into short pieces, so somehow the arec/aplay loop got desynced. I have been searching `dmesg` and other sources for a message that would make that desync detectable without actually listening to the sound, but had no success :frowning:.
* Fix: Just restart the acable, everything smooth again.

I never had that on my old implementation. So last night, I changed the acable script:

~~~
root@hifi:/usr/local/bin# diff acable.sh acable.sh_ORIG 
39,40c39,40
<       /usr/bin/arecord -D "$SR" -f "$FORMAT" -d "$DURATION" -t "$FILETYPE" | \
<       /usr/bin/aplay -D "$SINK" -f "$FORMAT" -d "$DURATION" -t "$FILETYPE"
---
>       /usr/bin/arecord -D "$SR" -f "$FORMAT" -d "$DURATION" -t "$FILETYPE" --buffer-size="$BUFFERSIZE" --period-size="$PERIODSIZE" | \
>       /usr/bin/aplay -D "$SINK" -f "$FORMAT" -d "$DURATION" -t "$FILETYPE" --buffer-size="$BUFFERSIZE" --period-size="$PERIODSIZE" 
~~~

I removed the explicit setting of the `--buffer-size` and `--period-size` so that both `arec` and `aplay` could choose their own defaults. This morning, no issue, everything exactly as I want to have it. I did not set the ansible values, so `acable` defaulted to the 8192/1024 setting in `acable.sh` before.

So either I have to find out what arec/aplay default to and change my ansible defaults. Or - and I would prefer that - we change the implementation of the default values: When no value is set in ansible, the parameter should not be passed to `arec`/`aplay` at all to get the proper default behaviour.

For  `-d`, `-f`, `-t` I guess the current behaviour is correct. So my proposal applies to the BUFFERSIZE/PERIODSIZE only.

**Comment by nis65** [comment]
Confirmation after 48 hours. Still stable audio:

~~~
root     16889 16845  0 Dec21 ?        00:19:04 /usr/bin/arecord -D dsnoop:CARD=sndrpihifiberry,DEV=0 -f cd -d 0 -t raw
root     16890 16845  0 Dec21 ?        00:18:09 /usr/bin/aplay -D dmix:CARD=Loopback,DEV=0 -f cd -d 0 -t raw
~~~

**Comment by Daenou** [comment]
> When no value is set in ansible, the parameter should not be passed to arec/aplay at all to get the proper default behaviour.

This is the preferred solution
