### ISSUE TITLE
Create README.md for every role

### ISSUE THREAD

**Issue by Daenou** [Daenou/ansible-multiroom-audio#9]

**Comment by nis65** [comment]
Where do you want to store these README.md files? in the role "root" directory (`/roles/a2dp_agent/README.md`) or do we create a subdir `/roles/a2dp_agent/doc/README.md`? I'd prefer the latter as it would allow to store diagrams along with the markdown file.

**Comment by nis65** [comment]
As discussed today: In order to publish the roles on ansible galaxy, we will need a README.md for every role anyway. So I'll create them e.g. here: `/roles/a2dp_agent/README.md`

**Comment by nis65** [comment]
Another naming issue occurred while writing documentation: should `base` be renamed to `asound-conf` or `dsnoop-dmix-defaults` ?

**Comment by Daenou** [comment]
> 
> 
> Another naming issue occurred while writing documentation: should `base` be renamed to `asound-conf` or `dsnoop-dmix-defaults` ?

As soon as we make the jump to separate roles in separate repositories and bundling these in a collection we'll have to rename the name of the `base` role anways. I agree with you, `asound-conf` sounds the best and doesn't limit us in the future.

**Comment by nis65** [comment]
Today, I successfully used the last two roles without `README.md, `snapserver`and `snd_aloop`. So I am ready now to start writing them soon...

**Comment by Daenou** [comment]
Functionality is in dev branch
